export default {
  name: "service",
  title: "Service",
  type: "document",
  fields: [
    { name: "name", title: "Service Name", type: "string", validation: (Rule: any) => Rule.required() },
    {
      name: "slug",
      title: "Slug (controls the page URL)",
      type: "slug",
      description:
        "This is what creates the link for this service — the card on the homepage and everywhere else links to /services/[this-slug]. Changing it changes the page's actual web address, so any existing links or bookmarks to the old URL will break.",
      options: { source: "name" },
      validation: (Rule: any) => Rule.required(),
    },
    { name: "icon", title: "Icon Name", type: "string", description: "react-icons/fi icon name, e.g. FiZap" },
    { name: "tagline", title: "Tagline", type: "string" },
    { name: "description", title: "Description", type: "text", rows: 4 },
    { name: "heroImage", title: "Hero Image", type: "image", options: { hotspot: true } },
    {
      name: "customQuote",
      title: "Custom Quote (no set price)",
      type: "boolean",
      initialValue: false,
      description: "Turn on to show \"Custom Quote\" instead of a starting price — hides the Starting Price field below.",
    },
    {
      name: "startingPrice",
      title: "Starting Price",
      type: "string",
      description: "Shown as \"From {this}\" — enter just the amount, e.g. $149.",
      hidden: ({ parent }: { parent?: { customQuote?: boolean } }) => Boolean(parent?.customQuote),
    },
    { name: "featured", title: "Featured on Homepage", type: "boolean", initialValue: false },
    { name: "benefits", title: "Benefits", type: "array", of: [{ type: "string" }] },
    { name: "process", title: "Process Steps", type: "array", of: [{ type: "string" }] },
    {
      name: "faqs",
      title: "FAQs",
      type: "array",
      of: [{ type: "reference", to: [{ type: "faq" }] }],
    },
    {
      name: "category",
      title: "Category",
      type: "reference",
      to: [{ type: "category" }],
    },
    { name: "order", title: "Sort Order", type: "number" },
    { name: "seo", title: "SEO", type: "seo" },
  ],
};
