// AUTO-GENERATED by scripts/fetch-sanity-content.mjs from Sanity (aboutPage document).
// Do not edit directly — edit content in the Sanity Studio instead, then re-run
// `npm run sync:sanity` (or just `npm run develop` / `npm run build`).

import {
  FiTarget,
  FiHeart,
  FiShield,
} from "react-icons/fi";

export const aboutPage = {
  heroHeadline: "Colorado-Owned.",
  heroHighlight: "Customer-Obsessed.",
  heroBody: "ClearPeak Exterior was founded on a simple idea: Denver Metro homeowners deserve an exterior cleaning company that shows up on time, does the job right, and treats every property like their own. Since then, we've grown into one of the area's most trusted names in residential and commercial exterior care.",
  heroImage: "https://cdn.sanity.io/images/vgi0saae/production/1559208971ddf7bef499d59eaa6a42869e2ac6b5-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
  valuesEyebrow: "What Drives Us",
  valuesTitle: "Built on Trust, Backed by Results",
  values: [
    { icon: FiTarget, title: "Our Mission", description: "To help every Denver Metro homeowner and business take pride in how their property looks — through honest, high-quality exterior cleaning." },
    { icon: FiHeart, title: "Our Values", description: "Integrity, craftsmanship, and genuine care for our customers' homes and the environment guide every job we take on." },
    { icon: FiShield, title: "Our Promise", description: "Fully insured, transparent pricing, and a satisfaction guarantee on every single service we provide." }
  ],
};
