// AUTO-GENERATED by scripts/fetch-sanity-content.mjs from Sanity (blogPost documents).
// Do not edit directly — edit content in the Sanity Studio instead, then re-run
// `npm run sync:sanity` (or just `npm run develop` / `npm run build`).

import type { BlogPost } from "~/types";

export const blogPosts: BlogPost[] = [
  {
    slug: "pressure-washing-vs-soft-washing",
    title: "Pressure Washing vs. Soft Washing: What's the Difference?",
    excerpt: "They're often used interchangeably, but pressure washing and soft washing are very different techniques suited to very different surfaces. Here's how to know which one your home needs.",
    category: "Education",
    author: "ClearPeak Team",
    date: "2026-03-04",
    readTime: "5 min read",
    heroImage: "https://cdn.sanity.io/images/vgi0saae/production/d0093a8963071291f2b0f6e89d38905c8b143d9e-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
    content: ["Pressure washing and soft washing are often used interchangeably, but they're fundamentally different techniques designed for different surfaces.", "Pressure washing uses high-PSI water to blast away dirt, grime, and stains from hard, durable surfaces like concrete, brick, and pavers. It's powerful, fast, and ideal for driveways, patios, and sidewalks.", "Soft washing, on the other hand, uses low pressure combined with specialized cleaning solutions to safely clean more delicate surfaces — like vinyl siding, stucco, painted wood, and roofing — without risking damage.", "The rule of thumb: if a surface can chip, crack, or strip under high pressure, it needs soft washing. If it's built to withstand force, pressure washing gets the job done faster and more thoroughly.", "At ClearPeak, we assess every surface individually and use the right method for the job — never a one-size-fits-all approach."],
  },
  {
    slug: "how-often-should-you-wash-your-house",
    title: "How Often Should You Wash Your House?",
    excerpt: "Colorado's dry summers, spring pollen, and winter grime all take a toll on your home's exterior. Here's a simple guide to how often you should be cleaning.",
    category: "Maintenance",
    author: "ClearPeak Team",
    date: "2026-02-18",
    readTime: "4 min read",
    heroImage: "https://cdn.sanity.io/images/vgi0saae/production/9131d22401ee30dbf46129c9edcd237015e60aef-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
    content: ["Most homes benefit from a full exterior wash once a year — but the right frequency depends on your home's location, sun exposure, and surrounding landscaping.", "Homes in shaded areas or near mature trees tend to accumulate mold and algae faster, and may need cleaning every 6–9 months.", "South- and west-facing walls that get more direct sun typically stay cleaner longer, while north-facing walls in the shade are prone to green and black staining.", "A good rule of thumb for Colorado homeowners: schedule your wash in late spring, after pollen season, to remove the seasonal buildup before summer entertaining begins."],
  },
  {
    slug: "best-time-to-wash-your-home-in-colorado",
    title: "The Best Time of Year to Wash Your Home in Colorado",
    excerpt: "Colorado's unique climate — dry winters, wet springs, and intense summer sun — affects the best time to schedule exterior cleaning. Here's what we recommend.",
    category: "Seasonal",
    author: "ClearPeak Team",
    date: "2026-01-22",
    readTime: "4 min read",
    heroImage: "https://cdn.sanity.io/images/vgi0saae/production/26e4bac0d3c0ab4972c25b027690f08f428b72f7-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
    content: ["Late spring (May–June) is the sweet spot for most Denver Metro homes — it's after the heaviest pollen and before peak summer heat, and it sets your home up looking great for the entire outdoor season.", "Fall cleaning (September–October) is a great second option, especially to clear off summer dust and prep your home before winter moisture sets in.", "We generally avoid washing during freezing temperatures, as water can freeze on surfaces and create ice hazards or, in rare cases, damage certain materials."],
  },
  {
    slug: "window-cleaning-tips",
    title: "5 Window Cleaning Tips for a Streak-Free Shine",
    excerpt: "Want your windows to sparkle between professional cleanings? These simple tips will help you keep them streak-free.",
    category: "Tips",
    author: "ClearPeak Team",
    date: "2026-01-08",
    readTime: "3 min read",
    heroImage: "https://cdn.sanity.io/images/vgi0saae/production/4de49f89a6b7b25383af39f7437d156ea62e458c-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
    content: ["Clean on a cloudy day. Direct sunlight dries cleaning solution too quickly, leaving streaks behind.", "Use a microfiber cloth or squeegee instead of paper towels, which can leave lint and streaks.", "Clean in a consistent direction — horizontal strokes on the outside, vertical on the inside — so you can spot which side a streak is on.", "Don't forget the frames and tracks; dirt here can wash back onto your freshly cleaned glass.", "For hard water spots, a vinegar-water solution can help break down mineral deposits before your next professional cleaning."],
  },
  {
    slug: "colorado-hard-water-stains",
    title: "Dealing with Colorado's Hard Water Stains on Your Exterior",
    excerpt: "Colorado's hard water leaves behind stubborn mineral deposits on windows, siding, and concrete. Here's what causes it and how to remove it safely.",
    category: "Education",
    author: "ClearPeak Team",
    date: "2025-12-14",
    readTime: "4 min read",
    heroImage: "https://cdn.sanity.io/images/vgi0saae/production/4004d7f44e706feeda2f75bcbc055a12b2d28877-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
    content: ["Much of the Denver Metro area has notably hard water, meaning it carries high concentrations of calcium and magnesium minerals.", "When hard water evaporates on windows, siding, or concrete, it leaves behind a cloudy, chalky mineral residue that regular rinsing won't remove.", "Professional-grade cleaning solutions formulated to dissolve mineral deposits — combined with proper technique — can restore surfaces without scratching or etching glass.", "Regular cleaning prevents hard water deposits from building up into permanent etching, especially on windows and glass railings."],
  },
  {
    slug: "how-much-does-pressure-washing-cost",
    title: "How Much Does Pressure Washing Cost in Denver?",
    excerpt: "Wondering what to budget for professional pressure washing? Here's a breakdown of typical pricing factors in the Denver Metro area.",
    category: "Pricing",
    author: "ClearPeak Team",
    date: "2025-11-30",
    readTime: "5 min read",
    heroImage: "https://cdn.sanity.io/images/vgi0saae/production/b44330a8c34b1ba688b15c1a7ed9001857475cdb-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
    content: ["Pressure washing costs typically depend on square footage, surface type, and level of buildup. Driveways generally range from $150–$300, while full house washes range from $250–$600.", "Surfaces with heavy staining, oil, or years of neglect may cost more due to additional pre-treatment time.", "Bundling services — like a driveway and patio together — often comes with a discount versus booking separately.", "Always get a free, itemized estimate before booking so there are no surprises on service day."],
  },
  {
    slug: "concrete-cleaning-guide",
    title: "The Complete Guide to Concrete Cleaning",
    excerpt: "From oil stains to hard water spots, here's everything you need to know about keeping your concrete surfaces looking their best.",
    category: "Guides",
    author: "ClearPeak Team",
    date: "2025-11-10",
    readTime: "6 min read",
    heroImage: "https://cdn.sanity.io/images/vgi0saae/production/5fa0609874908174eed111a38bebe009305d9067-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
    content: ["Concrete is porous, which means stains and organic growth can penetrate below the surface if left untreated for too long.", "Oil and rust stains require targeted pre-treatment before pressure washing to break down the stain at a molecular level.", "Algae and mildew commonly appear in shaded, damp areas — left untreated, they can make concrete slippery and hazardous.", "Sealing concrete after cleaning helps protect it from future staining and extends the time between deep cleanings."],
  },
  {
    slug: "roof-cleaning-guide",
    title: "The Complete Guide to Roof Cleaning",
    excerpt: "Those black streaks on your roof aren't just cosmetic — they can shorten your roof's lifespan. Here's what every homeowner should know.",
    category: "Guides",
    author: "ClearPeak Team",
    date: "2025-10-21",
    readTime: "6 min read",
    heroImage: "https://cdn.sanity.io/images/vgi0saae/production/2a7a863567c5e066189634b3b9a27314efe63a93-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
    content: ["Black streaks on asphalt shingles are typically caused by Gloeocapsa magma, an algae that feeds on limestone filler in shingles.", "Left untreated, this algae — along with moss and lichen — can trap moisture against your roof, shortening its lifespan.", "Professional roof cleaning uses a low-pressure, soft-wash method with an algaecidal solution, never high-pressure washing, which can dislodge granules and void shingle warranties.", "Regular roof cleaning every 2–3 years can significantly extend the life of your roofing investment."],
  }
];

export const getBlogPostBySlug = (slug: string) => blogPosts.find((p) => p.slug === slug);
