// AUTO-GENERATED by scripts/fetch-sanity-content.mjs from Sanity (brandColors document).
// Do not edit directly — edit content in the Sanity Studio instead, then re-run
// `npm run sync:sanity` (or just `npm run develop` / `npm run build`).

import type { BrandColors } from "~/types";

export const brandColors: BrandColors = {
  primary: "#00D4FF",
  secondary: "#FF4FA3",
  accent: "#FF7A59",
  ink: "#172B4D",
};
