// AUTO-GENERATED by scripts/fetch-sanity-content.mjs from Sanity (brandColors document).
// Do not edit directly — edit content in the Sanity Studio instead, then re-run
// `npm run sync:sanity` (or just `npm run develop` / `npm run build`).

import type { BrandColors } from "~/types";

export const brandColors: BrandColors = {
  primary: "#22D3EE",
  secondary: "#0F172A",
  accent: "#FB7185",
  onPrimary: "#0F172A",
  onPrimaryRgb: "15 23 42",
  onAccent: "#0F172A",
  onAccentRgb: "15 23 42",
};
