// AUTO-GENERATED by scripts/fetch-sanity-content.mjs from Sanity (contactPage document).
// Do not edit directly — edit content in the Sanity Studio instead, then re-run
// `npm run sync:sanity` (or just `npm run develop` / `npm run build`).

export const contactPage = {
  headline: "Let's Get Your Free Estimate",
  subheadline: "Fill out the form and we'll respond within one business hour with a free, no-obligation quote.",
};
