// AUTO-GENERATED by scripts/fetch-sanity-content.mjs from Sanity (faq documents (category == "General")).
// Do not edit directly — edit content in the Sanity Studio instead, then re-run
// `npm run sync:sanity` (or just `npm run develop` / `npm run build`).

import type { FAQItem } from "~/types";

export const faqs: FAQItem[] = [
  { question: "How much does exterior cleaning cost?", answer: "Pricing depends on the size of your property, the service selected, and the level of buildup. Most single-family homes range from $250–$600 for a full exterior refresh. We provide free, no-obligation estimates for an exact quote." },
  { question: "Is pressure washing safe for my home's siding and paint?", answer: "Traditional high-pressure washing can damage siding, paint, and stucco. That's why we use soft washing — low-pressure, eco-friendly cleaning — on delicate surfaces, and reserve full pressure for concrete, brick, and pavers." },
  { question: "How often should I have my home's exterior cleaned?", answer: "Most Colorado homes benefit from a full exterior cleaning once a year, ideally in spring or early summer. Homes in shaded, high-moisture, or high-pollen areas may need service every 6–9 months." },
  { question: "Are you licensed and insured?", answer: "Yes — ClearPeak Exteriors is fully licensed and insured for both residential and commercial work throughout the Denver Metro area. We're happy to provide proof of insurance upon request." },
  { question: "What areas do you service?", answer: "We proudly serve the greater Denver Metro area, including Denver, Littleton, Highlands Ranch, Castle Rock, Parker, Aurora, Lakewood, Centennial, Englewood, and Greenwood Village." },
  { question: "Do you use eco-friendly cleaning products?", answer: "Yes — our cleaning solutions are biodegradable and safe for landscaping, pets, and the environment. We also take care to pre-rinse and protect plants before treating nearby surfaces." },
  { question: "How do I get a quote?", answer: "Simply fill out our free estimate form or give us a call. We'll typically respond within one business hour with pricing, and can often schedule service within a few days." },
  { question: "What forms of payment do you accept?", answer: "We accept all major credit cards, debit cards, and digital payments. Payment is collected securely after your service is complete and you're satisfied with the results." }
];
