// AUTO-GENERATED by scripts/fetch-sanity-content.mjs from Sanity (footer document).
// Do not edit directly — edit content in the Sanity Studio instead, then re-run
// `npm run sync:sanity` (or just `npm run develop` / `npm run build`).

export const footerDescription = "Denver Metro's premium exterior cleaning company — pressure washing, soft washing, window cleaning, and more.";

export const footerColumns = [
  {
    heading: "Services",
    links: [
      { label: "Pressure Washing", href: "/services/pressure-washing" },
      { label: "House Soft Washing", href: "/services/house-soft-washing" },
      { label: "Window Cleaning", href: "/services/window-cleaning" },
      { label: "Roof Cleaning", href: "/services/roof-cleaning" },
      { label: "Concrete Cleaning", href: "/services/concrete-cleaning" },
      { label: "Commercial Services", href: "/services/commercial-services" }
    ],
  },
  {
    heading: "Service Areas",
    links: [
      { label: "Denver", href: "/service-areas/denver" },
      { label: "Littleton", href: "/service-areas/littleton" },
      { label: "Highlands Ranch", href: "/service-areas/highlands-ranch" },
      { label: "Castle Rock", href: "/service-areas/castle-rock" },
      { label: "Parker", href: "/service-areas/parker" },
      { label: "Aurora", href: "/service-areas/aurora" }
    ],
  },
  {
    heading: "Company",
    links: [
      { label: "About Us", href: "/about" },
      { label: "Gallery", href: "/gallery" },
      { label: "Blog", href: "/blog" },
      { label: "Contact", href: "/contact" }
    ],
  }
];

export const legalLinks = [
  { label: "Privacy Policy", href: "/privacy-policy" },
  { label: "Terms of Service", href: "/terms" }
];
