// AUTO-GENERATED by scripts/fetch-sanity-content.mjs from Sanity (galleryItem + beforeAfter documents).
// Do not edit directly — edit content in the Sanity Studio instead, then re-run
// `npm run sync:sanity` (or just `npm run develop` / `npm run build`).

import type { BeforeAfterItem, GalleryItem } from "~/types";

export const beforeAfterItems: BeforeAfterItem[] = [
  {
    id: "beforeAfter-ba-1",
    title: "Full House Soft Wash",
    service: "House Soft Washing",
    beforeImage: "https://cdn.sanity.io/images/vgi0saae/production/0940ab0326deae85f50e397f1ce29df5aa53250a-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
    afterImage: "https://cdn.sanity.io/images/vgi0saae/production/dccebf5e00f59b2baede21c7d4036790ad216e34-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "beforeAfter-ba-2",
    title: "Driveway Restoration",
    service: "Surface Pressure Washing",
    beforeImage: "https://cdn.sanity.io/images/vgi0saae/production/5fa0609874908174eed111a38bebe009305d9067-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
    afterImage: "https://cdn.sanity.io/images/vgi0saae/production/b44330a8c34b1ba688b15c1a7ed9001857475cdb-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "beforeAfter-ba-3",
    title: "Roof Algae Removal",
    service: "Roof Soft Washing",
    beforeImage: "https://cdn.sanity.io/images/vgi0saae/production/2a7a863567c5e066189634b3b9a27314efe63a93-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
    afterImage: "https://cdn.sanity.io/images/vgi0saae/production/f0cdd4ec5630212dd1fa5f4f8f22d64d85118f4a-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "beforeAfter-ba-4",
    title: "Patio Deep Clean",
    service: "Patio & Paver Cleaning",
    beforeImage: "https://cdn.sanity.io/images/vgi0saae/production/49555e025bab318e8283332b7ee590702a8f42bc-800x600.jpg?w=1600&h=1200&fit=crop&auto=format",
    afterImage: "https://cdn.sanity.io/images/vgi0saae/production/608f291a6ff250ab7629ef0142a351a60519a34b-800x600.jpg?w=1600&h=1200&fit=crop&auto=format",
  }
];

export const galleryItems: GalleryItem[] = [
  {
    id: "galleryItem-g-1",
    title: "Modern Home Soft Wash",
    category: "House Washing",
    image: "https://cdn.sanity.io/images/vgi0saae/production/87e388a4d03f01e5343139a1c21d6b45d0b0a3c5-800x600.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "galleryItem-g-2",
    title: "Driveway Pressure Wash",
    category: "Concrete",
    image: "https://cdn.sanity.io/images/vgi0saae/production/1c87e8698a2a9f1d8ccc0d16716bda15fba16770-800x600.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "galleryItem-g-3",
    title: "Sparkling Window Finish",
    category: "Windows",
    image: "https://cdn.sanity.io/images/vgi0saae/production/3b45afcfe708b37ed5d3b85629f6c461759b985d-800x600.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "galleryItem-g-4",
    title: "Roof Cleaning",
    category: "Roof",
    image: "https://cdn.sanity.io/images/vgi0saae/production/2a7a863567c5e066189634b3b9a27314efe63a93-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "galleryItem-g-5",
    title: "Backyard Patio Refresh",
    category: "Patios",
    image: "https://cdn.sanity.io/images/vgi0saae/production/e8b11bb4c90e9f9a91ad76d8a3b1b1a088f77646-1000x878.jpg?rect=0,64,1000,750&w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "galleryItem-g-6",
    title: "Deck Restoration",
    category: "Decks",
    image: "https://cdn.sanity.io/images/vgi0saae/production/e0e997964ce2f4df4cc31eff397bd147dbd77f3f-1000x667.jpg?rect=56,0,889,667&w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "galleryItem-g-7",
    title: "Commercial Storefront",
    category: "Commercial",
    image: "https://cdn.sanity.io/images/vgi0saae/production/5223feab05d723ceb2f4c698f93f7ab55ad2642f-800x600.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "galleryItem-g-8",
    title: "Poolside Cleaning",
    category: "House Washing",
    image: "https://cdn.sanity.io/images/vgi0saae/production/162d8be04ee4a40dd3fb7a52a80ef182e86a99c6-800x600.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "galleryItem-g-9",
    title: "Brick Exterior Wash",
    category: "House Washing",
    image: "https://cdn.sanity.io/images/vgi0saae/production/ffe107793f0e9d70951dc8452b48a7cad0b987a4-800x600.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "galleryItem-g-10",
    title: "Walkway Cleaning",
    category: "Concrete",
    image: "https://cdn.sanity.io/images/vgi0saae/production/f88188752e40b1faedfd082e06bff22e85014fda-800x600.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "galleryItem-g-11",
    title: "Front Entry Detail",
    category: "Windows",
    image: "https://cdn.sanity.io/images/vgi0saae/production/964cefda52391e51602421774b3a48d3b2345d0e-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "galleryItem-g-12",
    title: "Office Park Cleaning",
    category: "Commercial",
    image: "https://cdn.sanity.io/images/vgi0saae/production/b05411e844a60731aa7d61b40e9fab1098746419-800x600.jpg?w=1600&h=1200&fit=crop&auto=format",
  }
];
