// AUTO-GENERATED by scripts/fetch-sanity-content.mjs from Sanity (galleryItem + beforeAfter documents).
// Do not edit directly — edit content in the Sanity Studio instead, then re-run
// `npm run sync:sanity` (or just `npm run develop` / `npm run build`).

import type { BeforeAfterItem, GalleryItem } from "~/types";

export const beforeAfterItems: BeforeAfterItem[] = [
  {
    id: "beforeAfter-ba-1",
    title: "Full House Soft Wash",
    service: "House Soft Washing",
    beforeImage: "https://cdn.sanity.io/images/vgi0saae/production/0940ab0326deae85f50e397f1ce29df5aa53250a-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
    afterImage: "https://cdn.sanity.io/images/vgi0saae/production/dccebf5e00f59b2baede21c7d4036790ad216e34-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "beforeAfter-ba-2",
    title: "Driveway Restoration",
    service: "Pressure Washing",
    beforeImage: "https://cdn.sanity.io/images/vgi0saae/production/5fa0609874908174eed111a38bebe009305d9067-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
    afterImage: "https://cdn.sanity.io/images/vgi0saae/production/b44330a8c34b1ba688b15c1a7ed9001857475cdb-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "beforeAfter-ba-3",
    title: "Roof Algae Removal",
    service: "Roof Cleaning",
    beforeImage: "https://cdn.sanity.io/images/vgi0saae/production/2a7a863567c5e066189634b3b9a27314efe63a93-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
    afterImage: "https://cdn.sanity.io/images/vgi0saae/production/f0cdd4ec5630212dd1fa5f4f8f22d64d85118f4a-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "beforeAfter-ba-4",
    title: "Patio Deep Clean",
    service: "Patio Cleaning",
    beforeImage: "https://cdn.sanity.io/images/vgi0saae/production/d9c65542c00625bbe87f5e918527582e5a228d87-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
    afterImage: "https://cdn.sanity.io/images/vgi0saae/production/c994225b8128bfe816b211d6ea185b8095aab21f-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
  }
];

export const galleryItems: GalleryItem[] = [
  {
    id: "galleryItem-g-1",
    title: "Modern Home Soft Wash",
    category: "House Washing",
    image: "https://cdn.sanity.io/images/vgi0saae/production/dccebf5e00f59b2baede21c7d4036790ad216e34-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "galleryItem-g-2",
    title: "Driveway Pressure Wash",
    category: "Concrete",
    image: "https://cdn.sanity.io/images/vgi0saae/production/b44330a8c34b1ba688b15c1a7ed9001857475cdb-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "galleryItem-g-3",
    title: "Sparkling Window Finish",
    category: "Windows",
    image: "https://cdn.sanity.io/images/vgi0saae/production/df8944ef08003f1c8350b6ea76fa04c6e4ba1b18-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "galleryItem-g-4",
    title: "Roof Cleaning",
    category: "Roof",
    image: "https://cdn.sanity.io/images/vgi0saae/production/2a7a863567c5e066189634b3b9a27314efe63a93-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "galleryItem-g-5",
    title: "Backyard Patio Refresh",
    category: "Patios",
    image: "https://cdn.sanity.io/images/vgi0saae/production/c994225b8128bfe816b211d6ea185b8095aab21f-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "galleryItem-g-6",
    title: "Deck Restoration",
    category: "Decks",
    image: "https://cdn.sanity.io/images/vgi0saae/production/be5adfa46309b2cb4d54a55b65788c73c6b62b48-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "galleryItem-g-7",
    title: "Commercial Storefront",
    category: "Commercial",
    image: "https://cdn.sanity.io/images/vgi0saae/production/5bbbaf1f6c414cc1c955de318ced8c1562d7f6ae-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "galleryItem-g-8",
    title: "Poolside Cleaning",
    category: "House Washing",
    image: "https://cdn.sanity.io/images/vgi0saae/production/e7ef1c501e3aa5785d65102cecacaded4d3559fa-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "galleryItem-g-9",
    title: "Brick Exterior Wash",
    category: "House Washing",
    image: "https://cdn.sanity.io/images/vgi0saae/production/d9c65542c00625bbe87f5e918527582e5a228d87-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "galleryItem-g-10",
    title: "Walkway Cleaning",
    category: "Concrete",
    image: "https://cdn.sanity.io/images/vgi0saae/production/5fa0609874908174eed111a38bebe009305d9067-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "galleryItem-g-11",
    title: "Front Entry Detail",
    category: "Windows",
    image: "https://cdn.sanity.io/images/vgi0saae/production/964cefda52391e51602421774b3a48d3b2345d0e-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
  },
  {
    id: "galleryItem-g-12",
    title: "Office Park Cleaning",
    category: "Commercial",
    image: "https://cdn.sanity.io/images/vgi0saae/production/51558c13e8bdf4a414df007cb1136abe579081f6-1600x1200.jpg?w=1600&h=1200&fit=crop&auto=format",
  }
];
