// AUTO-GENERATED by scripts/fetch-sanity-content.mjs from Sanity (globalCta document).
// Do not edit directly — edit content in the Sanity Studio instead, then re-run
// `npm run sync:sanity` (or just `npm run develop` / `npm run build`).

import type { GlobalCtaContent } from "~/types";

export const globalCta: GlobalCtaContent = {
  headline: "Ready to Refresh Your Home?",
  subtext: "Get a free, no-obligation estimate today and see why Denver homeowners trust ClearPeak Exterior.",
  primaryCta: { label: "Get My Free Quote", url: "/contact", style: "white" },
  secondaryCta: { label: "Call Today", url: "tel:+3033969904", style: "outline" },
};
