// AUTO-GENERATED by scripts/fetch-sanity-content.mjs from Sanity (homepage document).
// Do not edit directly — edit content in the Sanity Studio instead, then re-run
// `npm run sync:sanity` (or just `npm run develop` / `npm run build`).

import type { HomepageContent } from "~/types";

export const homepage: HomepageContent = {
  heroEyebrow: "Now Booking — Denver Metro",
  heroHeadline: "Bring Your Home",
  heroHighlight: "Back to Life.",
  heroSubheadline: "Denver's premium exterior cleaning company specializing in pressure washing, soft washing, window cleaning, and exterior restoration.",
  heroPrimaryCta: { label: "Get Free Estimate", url: "/contact", style: "primary" },
  heroSecondaryCta: { label: "View Our Work", url: "/gallery", style: "white" },
  trustBadges: ["Fully Insured", "Locally Owned", "Satisfaction Guaranteed", "Five-Star Rated"],
};
