// AUTO-GENERATED by scripts/fetch-sanity-content.mjs from Sanity (navigation document).
// Do not edit directly — edit content in the Sanity Studio instead, then re-run
// `npm run sync:sanity` (or just `npm run develop` / `npm run build`).

import type { CtaButton } from "~/types";

export const navLinks = [
  { label: "Services", href: "/services" },
  { label: "Gallery", href: "/gallery" },
  { label: "Service Areas", href: "/service-areas" },
  { label: "Blog", href: "/blog" },
  { label: "About", href: "/about" }
];

export const headerCta: CtaButton = { label: "Get Free Estimate", url: "/contact", style: "secondary" };
