// AUTO-GENERATED by scripts/fetch-sanity-content.mjs from Sanity (promotion documents).
// Do not edit directly — edit content in the Sanity Studio instead, then re-run
// `npm run sync:sanity` (or just `npm run develop` / `npm run build`).

import type { Promotion } from "~/types";

export const promotions: Promotion[] = [

];
