// AUTO-GENERATED by scripts/fetch-sanity-content.mjs from Sanity (promotion documents).
// Do not edit directly — edit content in the Sanity Studio instead, then re-run
// `npm run sync:sanity` (or just `npm run develop` / `npm run build`).

import type { Promotion } from "~/types";

export const promotions: Promotion[] = [
  {
    title: "Testing Promo",
    message: "get a discount text",
    cta: { label: "contact us ", url: "/contact", style: "primary" },
    startDate: "2026-07-08",
    endDate: "2026-07-15",
    active: true,
    placement: "Top Banner",
  }
];
