// AUTO-GENERATED by scripts/fetch-sanity-content.mjs from Sanity (siteContent document).
// Do not edit directly — edit content in the Sanity Studio instead, then re-run
// `npm run sync:sanity` (or just `npm run develop` / `npm run build`).

export const siteContent = {
  servicesSection: { eyebrow: "What We Do", title: "Full-Service Exterior Cleaning", description: "From your roofline to your driveway, we've got every exterior surface covered — with the equipment, expertise, and care to do it right." },
  beforeAfterSection: { eyebrow: "Real Results", title: "See the ClearPeak Difference", description: "Drag the slider to see the transformation. These are real results from real Denver Metro properties." },
  gallerySection: { eyebrow: "Our Work", title: "A Portfolio of Transformations", description: "Browse real projects across the Denver Metro area — filter by service to find exactly what you're looking for." },
  reviewsSection: { eyebrow: "Reviews", title: "Loved by Homeowners Across Denver", description: "" },
  serviceAreasSection: { eyebrow: "Where We Work", title: "Proudly Serving the Denver Metro Area", description: "Click your city to see local pricing, neighborhoods we serve, and service availability." },
  blogSection: { eyebrow: "From the Blog", title: "Tips, Guides & Local Know-How", description: "Practical advice on keeping your Colorado home looking its best, all year long." },
  faqSection: { eyebrow: "FAQ", title: "Frequently Asked Questions", description: "" },
};
