// AUTO-GENERATED by scripts/fetch-sanity-content.mjs from Sanity (siteSettings document).
// Do not edit directly — edit content in the Sanity Studio instead, then re-run
// `npm run sync:sanity` (or just `npm run develop` / `npm run build`).

export const site = {
  name: "ClearPeak Exteriors",
  tagline: "Denver's Premium Exterior Cleaning Company",
  phone: "(720) 555-0182",
  phoneHref: "tel:+17205550182",
  email: "hello@clearpeakexteriors.com",
  address: {
    street: "4200 W 38th Ave, Suite 210",
    city: "Denver",
    state: "CO",
    zip: "80212",
  },
  social: {
    facebook: "https://facebook.com/clearpeakexteriors",
    instagram: "https://instagram.com/clearpeakexteriors",
    google: "https://g.page/clearpeakexteriors",
  },
  hours: "Mon–Sat: 7:00am – 7:00pm",
  quoteFormUrl: "/contact",
  rating: 4.9,
  reviewCount: 312,
};
