// AUTO-GENERATED by scripts/fetch-sanity-content.mjs from Sanity (siteSettings document).
// Do not edit directly — edit content in the Sanity Studio instead, then re-run
// `npm run sync:sanity` (or just `npm run develop` / `npm run build`).

export const site = {
  name: "ClearPeak Exterior",
  tagline: "Denver's Premium Exterior Cleaning Company",
  phone: "(303) 396-9904",
  phoneHref: "tel:+13033969904",
  email: "luke.hinrichs@gmail.com",
  address: {
    street: "4200 W 38th Ave, Suite 210",
    city: "Denver",
    state: "CO",
    zip: "80211",
  },
  social: {
    facebook: "https://www.facebook.com/profile.php?id=61591666452703",
    instagram: "https://instagram.com/clearpeakexteriors",
    google: "https://g.page/clearpeakexteriors",
  },
  hours: "Mon–Sat: 7:00am – 9:00pm",
  quoteFormUrl: "/contact",
  rating: 0,
  reviewCount: 0,
};
