// AUTO-GENERATED by scripts/fetch-sanity-content.mjs from Sanity (testimonial documents).
// Do not edit directly — edit content in the Sanity Studio instead, then re-run
// `npm run sync:sanity` (or just `npm run develop` / `npm run build`).

import type { Testimonial } from "~/types";

export const testimonials: Testimonial[] = [

];
