// AUTO-GENERATED by scripts/fetch-sanity-content.mjs from Sanity (trustBadgesSection document).
// Do not edit directly — edit content in the Sanity Studio instead, then re-run
// `npm run sync:sanity` (or just `npm run develop` / `npm run build`).

import {
  FiShield,
  FiHome,
  FiThumbsUp,
  FiStar,
} from "react-icons/fi";

export const trustBadgesSection = {
  badges: [
    { icon: FiShield, label: "Fully Insured" },
    { icon: FiHome, label: "Locally Owned" },
    { icon: FiThumbsUp, label: "Satisfaction Guaranteed" },
    { icon: FiStar, label: "Five-Star Rated" }
  ],
  stats: [
    { value: 3200, suffix: "+", label: "Homes Cleaned", decimal: false },
    { value: 4.9, suffix: "★", label: "Average Rating", decimal: true },
    { value: 10, suffix: "+", label: "Cities Served", decimal: false },
    { value: 8, suffix: " yrs", label: "In Business", decimal: false }
  ],
};
