// AUTO-GENERATED by scripts/fetch-sanity-content.mjs from Sanity (whyChooseUsSection document).
// Do not edit directly — edit content in the Sanity Studio instead, then re-run
// `npm run sync:sanity` (or just `npm run develop` / `npm run build`).

import {
  FiTool,
  FiFeather,
  FiClock,
  FiHeart,
  FiDollarSign,
  FiTarget,
  FiHome,
} from "react-icons/fi";

export const whyChooseUsSection = {
  eyebrow: "Why ClearPeak",
  title: "Higher Standards, Better Results",
  description: "We built ClearPeak to be the exterior cleaning company Denver homeowners actually recommend to their neighbors.",
  reasons: [
    { icon: FiTool, title: "Professional Equipment", description: "Commercial-grade pressure washers and soft-wash systems calibrated for every surface type." },
    { icon: FiFeather, title: "Eco-Friendly Products", description: "Biodegradable cleaning solutions that are safe for your family, pets, and landscaping." },
    { icon: FiClock, title: "Fast Response", description: "Most estimate requests are answered within one business hour, with flexible scheduling." },
    { icon: FiHeart, title: "Premium Customer Service", description: "Friendly, communicative crews who treat your property like their own." },
    { icon: FiDollarSign, title: "Transparent Pricing", description: "Upfront, itemized quotes with no hidden fees or last-minute upsells." },
    { icon: FiTarget, title: "Attention to Detail", description: "From tracks and sills to corners and edges, we don't cut corners — literally." },
    { icon: FiHome, title: "Locally Owned", description: "Proudly Denver-based and invested in the community we serve every day." }
  ],
};
